Set RunAtLoad to false in macOS launchd configuration
kolide/launcher pull request #653
Opened 2020-09-11 20:23 UTC by zwass

The existing behavior conflicted with the KeepAlive configuration that
only starts the daemon if the enroll secret path is present.

Setting this option to false leaves the general case the same: If a
package includes an enroll secret, the daemon is started immediately on
completion of install.

Setting this option to false allows the less-common case to work as
intended: The daemon will only start after an enroll secret is written
to the expected path.

The previous behavior would be to start the daemon even if no enroll
secret exists, and the daemon would then promptly exit with a nonzero status.

2020-09-15 03:17 UTC, directionless commented
(I want to test this on a spare machine. I'll try to get to it this week)

2020-09-16 15:35 UTC, directionless requested changes
I tested this on my test Big Sur machine and ran into some issues. Or perhaps, this uncovered existing ones.

The logs with this set had some errors along the lines of https://github.com/kolide/launcher/issues/232

2020-09-16 16:36 UTC, zwass commented
@directionless Do the errors go away when RunAtLoad is set? I'm not sure how that key could have any interaction with DNS resolution. If you actually saw the service start up (or try to) then I think that demonstrates this PR working as intended.

2020-09-16 17:18 UTC, directionless commented
> Do the errors go away when RunAtLoad is set? 

Yes. It works when RunAtLoad is set. I agree this is confusing.

I would theorize that either it changes the startup order. But it's not something I can debug just now.

2021-02-18 21:07 UTC, zwass commented
I am not working any further on this.

2021-02-18 21:07 UTC, closed without merging