Add secedit virtual table for windows
kolide/launcher pull request #657
Opened 2020-09-14 18:45 UTC by terracatta

This PR adds a new table called `kolide_secedit` to launcher which provides access to the output created by `secedit.exe` on windows.

Example Query: `select * from kolide_secedit where area = "SecurityPolicy";` (note the `area` column is required)

Example Output (truncated)

```
+----------------+---------------+------------------------------+---------------+
| area           | section       | key                          | value         |
+----------------+---------------+------------------------------+---------------+
| SecurityPolicy | Unicode       | Unicode                      | yes           |
| SecurityPolicy | System Access | MinimumPasswordAge           | 0             |
| SecurityPolicy | System Access | MaximumPasswordAge           | 42            |
| SecurityPolicy | System Access | MinimumPasswordLength        | 0             |
| SecurityPolicy | System Access | PasswordComplexity           | 1             |
| SecurityPolicy | System Access | PasswordHistorySize          | 0             |
| SecurityPolicy | System Access | LockoutBadCount              | 0             |
| SecurityPolicy | System Access | RequireLogonToChangePassword | 0             |
| SecurityPolicy | System Access | ForceLogoffWhenHourExpire    | 0             |
| SecurityPolicy | System Access | NewAdministratorName         | Administrator |
| SecurityPolicy | System Access | NewGuestName                 | Guest         |
| SecurityPolicy | System Access | ClearTextPassword            | 0             |
| SecurityPolicy | System Access | LSAAnonymousNameLookup       | 0             |
| SecurityPolicy | System Access | EnableAdminAccount           | 0             |
| SecurityPolicy | System Access | EnableGuestAccount           | 0             |
| SecurityPolicy | Event Audit   | AuditSystemEvents            | 0             |
| SecurityPolicy | Event Audit   | AuditLogonEvents             | 0             |
| SecurityPolicy | Event Audit   | AuditObjectAccess            | 0             |
| SecurityPolicy | Event Audit   | AuditPrivilegeUse            | 0             |
| SecurityPolicy | Event Audit   | AuditPolicyChange            | 0             |
+----------------+---------------+------------------------------+---------------+
```

2020-09-14 21:05 UTC, terracatta commented
@directionless will add your dataflatten library to this once you merge.

2020-09-15 01:48 UTC, directionless requested changes
Looks really good. 

With https://github.com/kolide/launcher/pull/655 merged, I'd say lets use that. I think this works, but I think there's value in consistency. 

Couple of other questions in line

2020-09-15 13:48 UTC, terracatta commented on pkg/osquery/tables/secedit/secedit.go
> +	}
I didn't realize this! Nice catch, removing this constraint because we truly want everything we can get.

2020-09-15 13:57 UTC, terracatta commented on pkg/osquery/tables/secedit/secedit.go
> +	cmd := exec.CommandContext(ctx, "secedit", "/export", "/areas", area, "/cfg", dst)
Adding this flag causes it to remove all useful output, I'm not sure why but my hunch is if the device isn't on domain it just returns no settings? No idea...

2020-09-15 14:16 UTC, directionless reviewed
Looks really good. I could be persuaded to merge as is, though I have some interested in renaming `section` to `parent`. (Consistency there will make it easier as I add more helpers to remove the boilerplate)

I think we probably should add a mergedpolicy option too

2020-09-15 14:16 UTC, directionless commented on pkg/osquery/tables/secedit/secedit.go
> +		table.TextColumn("section"),
```suggestion
		table.TextColumn("parent"),
```

I _think_ I'd rather we used our defacto standard naming of `parent` and `key`, even though I agree `section` is more correct for the data. I can be convinced, but I mostly favor consistency.

2020-09-15 14:16 UTC, directionless commented on pkg/osquery/tables/secedit/secedit.go
> +			s, k := row.ParentKey("/")
```suggestion
			p, k := row.ParentKey("/")
```
(as above)

2020-09-15 14:16 UTC, directionless commented on pkg/osquery/tables/secedit/secedit.go
> +				"section": s,
```suggestion
				"parent": p,
```
(as above)

2020-09-15 16:30 UTC, directionless approved these changes
Looks great. Let's try it!

2020-09-15 16:32 UTC, merged